// <auto-generated />
namespace _2014118209_PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Prueba1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Prueba1));
        
        string IMigrationMetadata.Id
        {
            get { return "201705141633055_Prueba 1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
