//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2014118209_API.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public int ServicioId { get; set; }
        public int LugarViajeId { get; set; }
        public int BusId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> TipoViaje { get; set; }
        public string Beneficiario { get; set; }
        public Nullable<double> Peso { get; set; }
        public string Discriminator { get; set; }
    
        public virtual Buses Buses { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual LugarViajes LugarViajes { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
